<a href="https://colab.research.google.com/github/Leshan21/Deep-Learning/blob/main/Deep_Learning_00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook, we are going to cover some of the fundamental concepts of tensors uning Tensorflow

More specifically, we're going to cover:
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & Numpy
* Unsing @tf.function (a way to speed up your regular python function)
* Using GPUs with Tensorflow (or TPUs?)
* Exercises to try yourself

In [3]:
# import tensorflow
import tensorflow as tf
print(tf.__version__)

2.19.0


In [ ]:
# create tensorflow with tf.constant()

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# check the number of dimensions ofa tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [ ]:
# create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# check the dimension of our vector
vector.ndim

1

In [ ]:
# create a matrix (has more than 1 dimension)
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
 matrix.ndim

2

In [ ]:
# create another matrix
another_matrix = tf.constant([[10. , 7.],
                              [3.,2.],
                              [8., 9.]], dtype = tf.float16) # specify the datatype
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
# whats the number dimensions of another_matrix?

another_matrix.ndim

2

In [ ]:
# Let's create tensor

tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
 tensor.ndim

3

# What we've created so far:

* Scalar: a single number
* vector: a number with direction (eg: wind speed and direction)
* Matrix: a 2-dimension array of numbers
* Tensor: an n-dimensional array of numbers(when n can be number, a 0-dimensional tensor is a scalar, a 1 dimensional tensor is a vectoe )

# Create tensor with "tf.variable"

In [7]:
# create the same tensor with tf.Variable() as above

changeble_tensor = tf.Variable([10, 7])
unchangeble_tensoe = tf.constant([10, 7])
changeble_tensor, unchangeble_tensoe

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [8]:
# Let's try change one of the elements in our changeble tensor

changeble_tensor[0] = 7
changeble_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [10]:
# How about we try .assign()

changeble_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [14]:
# Let's try change unchangeble tensor

unchangeble_tensoe[0].assign(7)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'